config/routes.rb
Rails.application.routes.draw do
  resources :product_tags
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resources :orders
  resources :creators
  resources :product_sizes
  resources :variants
  resources :products
  resources :stocks

  get '/home/payout/:code', to: 'home#payout', as: 'payout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/creator.rb
class Creator < ApplicationRecord
    has_many :orders

    enum profit_share: { :revenue => 0, :profit => 1 }
    
    before_save do
       self.code = self.code.downcase 
    end
end

app/controllers/creators_controller.rb
class CreatorsController < ActionController::Base
  before_action :set_creator, only: [:show, :edit, :update, :destroy]

  # GET /creators
  # GET /creators.json
  def index
    @creators = Creator.all
  end

  # GET /creators/1
  # GET /creators/1.json
  def show
    @orders = Order.where(:creator => @creator)
  end

  # GET /creators/new
  def new
    @creator = Creator.new
  end

  # GET /creators/1/edit
  def edit
  end

  # POST /creators
  # POST /creators.json
  def create
    @creator = Creator.new(creator_params)

    respond_to do |format|
      if @creator.save
        format.html { redirect_to @creator, notice: 'Creator was successfully created.' }
        format.json { render :show, status: :created, location: @creator }
      else
        format.html { render :new }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creators/1
  # PATCH/PUT /creators/1.json
  def update
    respond_to do |format|
      if @creator.update(creator_params)
        format.html { redirect_to @creator, notice: 'Creator was successfully updated.' }
        format.json { render :show, status: :ok, location: @creator }
      else
        format.html { render :edit }
        format.json { render json: @creator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creators/1
  # DELETE /creators/1.json
  def destroy
    @creator.destroy
    respond_to do |format|
      format.html { redirect_to creators_url, notice: 'Creator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creator
      @creator = Creator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creator_params
      params.require(:creator).permit(:name, :code, :profit_share, :share)
    end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/_form.html.erb
<%= form_with(model: creator, local: true) do |form| %>
  <% if creator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creator.errors.count, "error") %> prohibited this creator from being saved:</h2>

      <ul>
      <% creator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>
  <div class="field">
    <%= form.select :profit_share, Creator.profit_shares.keys.to_a %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/creators/edit.html.erb
<h1>Editing Creator</h1>

<%= render 'form', creator: @creator %>

<%= link_to 'Show', @creator %> |
<%= link_to 'Back', creators_path %>

app/views/creators/index.html.erb
<%= render 'shared/flash' %>

<br>

  <h1>Influencers</h1>
<div class="card">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Name</th>
          <th>Code</th>
          <th>Share from</th>
          <th>Percentage</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @creators.each do |creator| %>
          <tr>
            <td><%= creator.name %></td>
            <td><%= creator.code %></td>
            <td>
              <% if creator.profit?  %>
                Revenue
              <% else %>
                Profit
              <% end %>
            </td>
            <td><%= creator.share %>%</td>
            <td><%= link_to 'Show', creator %></td>
            <td><%= link_to 'Edit', edit_creator_path(creator) %></td>
            <td><%= link_to 'Destroy', creator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'New Creator', new_creator_path, {:class => 'btn btn-primary'} %>

app/views/creators/new.html.erb
<h1>New Creator</h1>

<%= render 'form', creator: @creator %>

<%= link_to 'Back', creators_path %>

app/views/creators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @creator.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @creator.code %>
</p>

<%= link_to 'Edit', edit_creator_path(@creator) %> |
<%= link_to 'Back', creators_path %>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_id %></td>
        <td><%= order.creator %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>