config/routes.rb
Rails.application.routes.draw do
  resources :product_tags
  root :to => 'home#index'
  mount ShopifyApp::Engine, at: '/'
  resources :orders
  resources :creators
  resources :product_sizes
  resources :variants
  resources :products
  resources :stocks

  get '/home/payout/:code', to: 'home#payout', as: 'payout'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
end

app/controllers/product_tags_controller.rb
class ProductTagsController < ApplicationController
  before_action :set_product_tag, only: [:show, :edit, :update, :destroy]

  # GET /product_tags
  # GET /product_tags.json
  def index
    @product_tags = ProductTag.all
  end

  # GET /product_tags/1
  # GET /product_tags/1.json
  def show
  end

  # GET /product_tags/new
  def new
    @product_tag = ProductTag.new
  end

  # GET /product_tags/1/edit
  def edit
  end

  # POST /product_tags
  # POST /product_tags.json
  def create
    @product_tag = ProductTag.new(product_tag_params)

    respond_to do |format|
      if @product_tag.save
        format.html { redirect_to @product_tag, notice: 'Product tag was successfully created.' }
        format.json { render :show, status: :created, location: @product_tag }
      else
        format.html { render :new }
        format.json { render json: @product_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_tags/1
  # PATCH/PUT /product_tags/1.json
  def update
    respond_to do |format|
      if @product_tag.update(product_tag_params)
        format.html { redirect_to @product_tag, notice: 'Product tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_tag }
      else
        format.html { render :edit }
        format.json { render json: @product_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_tags/1
  # DELETE /product_tags/1.json
  def destroy
    @product_tag.destroy
    respond_to do |format|
      format.html { redirect_to product_tags_url, notice: 'Product tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_tag
      @product_tag = ProductTag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_tag_params
      params.require(:product_tag).permit(:tag)
    end
end

app/helpers/product_tags_helper.rb
module ProductTagsHelper
end

app/views/product_tags/_form.html.erb
<%= form_with(model: product_tag, local: true) do |form| %>
  <% if product_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_tag.errors.count, "error") %> prohibited this product_tag from being saved:</h2>

      <ul>
      <% product_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_tags/edit.html.erb
<h1>Editing Product Tag</h1>

<%= render 'form', product_tag: @product_tag %>

<%= link_to 'Show', @product_tag %> |
<%= link_to 'Back', product_tags_path %>

app/views/product_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Tags</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_tags.each do |product_tag| %>
      <tr>
        <td><%= product_tag.tag %></td>
        <td><%= link_to 'Show', product_tag %></td>
        <td><%= link_to 'Edit', edit_product_tag_path(product_tag) %></td>
        <td><%= link_to 'Destroy', product_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Tag', new_product_tag_path %>

app/views/product_tags/new.html.erb
<h1>New Product Tag</h1>

<%= render 'form', product_tag: @product_tag %>

<%= link_to 'Back', product_tags_path %>

app/views/product_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @product_tag.tag %>
</p>

<%= link_to 'Edit', edit_product_tag_path(@product_tag) %> |
<%= link_to 'Back', product_tags_path %>